name: Periodic Checks on main
on:
  schedule:
    # Triggers the workflow weekdays at 9:00 UTC
    - cron: '0 9 * * MON-FRI'
  workflow_dispatch:

jobs:
  markdown-link-check:
    name: Check Markdown links
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check links in *.md files
        run: ./hack/check-links.sh
